### ISSUE TITLE
Cannot load iron module

### ISSUE THREAD

**Issue by wbthomason** [Vigemus/iron.nvim#125]
When I try to load `iron` (either via `require('iron')` in my config or by calling any of the commands, e.g. `:IronRepl`), I get the following error:

`E5105: Error while calling lua chunk: ~/.config/nvim/lua/iron.lua:1: loop or previous error loading module 'iron'`

I'm not quite sure how to go about debugging this. I suspect maybe an issue with the package loading (I'm using the native packages feature), but I'm not really sure where to start tracking down what would cause this.

**Comment by hkupty** [comment]
Hi,

Sorry for taking long to answer.

I suspect this is caused by some path configuration maybe, as your messages states `~/.config/nvim/lua/iron.lua` whereas I'd expect something like `~/.config/nvim/plugins/iron/lua/iron.lua`.

I'm not really sure how neovim sets up paths for lua projects, but apparently, according to the docs, it adjusts the paths from your runtimepath:

```
Nvim automatically adjusts `package.path` and `package.cpath` according to
effective 'runtimepath' value.  Adjustment happens whenever 'runtimepath' is
changed.  `package.path` is adjusted by simply appending `/lua/?.lua` and
`/lua/?/init.lua` to each directory from 'runtimepath' (`/` is actually the
first character of `package.config`).
```

So I'd check how your native packages is configured first.

**Comment by wbthomason** [comment]
Thanks, good call! There was indeed some nonsense going on with my path config causing the `lua/iron.lua` file (which was config for `iron.nvim`) to be loaded instead of `path/to/native/packages/start/iron.nvim/lua/iron.lua`. Everything works again with that file removed. Thanks again, and thanks for the great plugin!

**Comment by hkupty** [comment]
Amazing!

Thank you very much for your issue.

Best,
Henry
