### ISSUE TITLE
Starting IronRepl thows lua error

### ISSUE THREAD

**Issue by syntaxman** [Vigemus/iron.nvim#141]
I have installed iron.nvim using vim-plug and the native package facility.  If I define luafile in init.vim, and provide a plugins.lua file, the require('iron') line throws errors about not finding the module.  All other modules are found and my $packpath is sane.  If I run :IronRepl, I get the following error:
 
E5105: Error while calling lua chunk: ...im/site/pack/iron.nvim/start/iron.nvim/lua/iron/init.lua:91: bad argument #1 to 'pairs' (table expected, got nil)

This happens regardless of what I do with defining the luafile in init.vim.  I also noticed that the help file isn't being loaded.

**Comment by wbthomason** [comment]
By "using vim-plug and the native package facility", do you mean that you've installed iron.nvim _twice_? This could cause some trouble, though it shouldn't cause the errors you've reported.

If you're using the native package feature to install iron, are you installing it as an optional or startup package? If it's optional, have you called `packadd iron.nvim` before attempting to `require('iron')`? That - not having the package added before attempting to configure it - caused me to see errors about not finding the module.

**Comment by syntaxman** [comment]
I installed all my plugins, including iron.nvim, using vim-plug. When that didn't work, I tried the native pkg facility.  I got the same errors with both methods.  I'm back to using vim-plug.

My init.vim says:
  Plug 'Vigemus/iron.nvim'                
  luafile $HOME/.config/nvim/plugins.lua  

I did add the "packadd iron.nvim" directive to the top of plugins.lua, and that helped a lot.  I have one error left:
Error detected while processing /home/wade/.config/nvim/init.vim: line   79:
E5112: Error while creating lua chunk: /home/wade/.config/nvim/plugins.lua:1: '=' expected near 'iron'

  The first two lines of plugins.lua are:
packadd iron.vim                                                                       
local iron = require('iron')

Fortunately this doesn't prevent getting to the REPL.  Not sure yet if it causes any errors.

**Comment by wbthomason** [comment]
`packadd` is a Vimscript command, not valid Lua. That is probably what's causing your remaining error. That said, it shouldn't be necessary - `vim-plug` doesn't use the native package system, and (per the `init.vim` snippet you sent) you're not even lazy-loading iron.nvim.

Since you're using `vim-plug`, there's one other sanity check: Do you call `call plug#end()` *after* your `Plug 'Vigemus/iron.nvim'` line but *before* your `luafile ...` line? iirc (it's been a while since I used `vim-plug`) that's necessary in order for plugins to actually be loaded.

Also, make sure you've deleted the directory from your attempt to install iron.nvim with the native package functionality.

**Comment by syntaxman** [comment]
Thank you!  Moving the luafile line outside the plugin section was the solution.  And, of course, I no longer needed a packadd line anywhere.
