### ISSUE TITLE
Python version and virtualenv support

### ISSUE THREAD

**Issue by silenc3r** [Vigemus/iron.nvim#25]
1. Provide an option to launch chosen version of Python repl. I think `:IronRepl` should use default Python version, while `:IronPromptRepl` should let you choose between `python`, `python2`, `python3`, with `python` being alias for default Python version.

2. When run inside virtualenv `:IronRepl` should choose appropriate Python version.

**Comment by hkupty** [comment]
Hey,

Thanks for the issue. 

This is something I've been thinking about for a while and it's on my plans.

I'll try to come up with something more concrete in the next few days.

Cheers!

**Comment by hkupty** [comment]
Thanks for taking this long to answer.

I've just added an option (on `testing` branch) repls can have precedence over others and return in a more deterministic way. The remaining part is a tie break, where you're prompted for a client if two have the same priorities. One example of such would be `ipython` having the more priority over `python`, but the same priority of `ipython2`.

`:IronPromptRepl` does allow you to specify python version, if, for instance, you supply `python2` (which on many systems is a binary) it'll run python2 instead. It actually allows you to call any exectuable, such as `./shell` or `python manage.py shell`.

As for virtualenv support, this is a bit tricky since neovim should've been started after `source .venv/bin/activate`. I'm not sure I can use it without sourcing first.. I'll do some research and try to set it up without explicit need of starting nvim from within a sourced env.

**Comment by silenc3r** [comment]
It still doesn't work for me. When I run ```IronRepl``` inside python3 virtualenv I get python2 repl. When I try to run ```IronPromptRepl``` specifying python3 or ipython3 I get ```Unable to find repl for python3```.  
I got these at top of my ```init.vim```

    let g:python_version = matchstr(system("python --version | cut -f2 -d' '"), '^[0-9]')
    let g:python2_host_prog = "/usr/bin/python2"
    let g:python3_host_prog = "/usr/bin/python3"

**Comment by hkupty** [comment]
I'll take a look at that.. I'm sorry it doesn't work..

**Comment by hkupty** [comment]
Hi,

I'm closing this issue since it is roughly solved in the new Lua infrastructure. Check #94 for more information.

Cheers
