### ISSUE TITLE
how to move back to code?

### ISSUE THREAD

**Issue by mohelm** [Vigemus/iron.nvim#86]
Hi, 

I would like to use use your program but I am having issues moving back from the ipython console to the code area (buffer)? 

Can you help me with this real quick? Many thanks and sorry about this stupid question.

**Comment by hkupty** [comment]
Hi. Thanks for the issue.

This is a neovim feature (the terminal and related bindings). In order to leave the terminal, you should type `<C-\><C-n>` to leave terminal mode. From there, you can `<C-w>l` to move between windows as you normally would.

If you have used tmux before, I recommend you taking a look at [nvimux] (https://github.com/Vigemus/nvimux). It binds `<C-b>[` to exit to normal mode.

And don't refrain from asking, even if you think your question is stupid. No one is obliged to know.

Cheers,
Henry John Kupty

**Comment by mohelm** [comment]
Hi Henry. Many thanks for the reply! :-)

I will have a look at nvimux.

**Comment by hkupty** [comment]
Glad I could help!

I'll close the issue now, but feel free to reopen or open a new one if you have any other doubts.

Cheers
