### ISSUE TITLE
Install, Error when UpdateRemotePlugins

### ISSUE THREAD

**Issue by benignoc** [Vigemus/iron.nvim#89]
Hello, I am finding an error when executing UpdateRemotePlugins, which results in not having the commands available (IronRepl etc... only see two commands: IronUnwatchCurrentFile and IronWatchCurrentFile).
The error I get when executing UpdateRemotePlugins is:

`Encountered ModuleNotFoundError loading plugin at C:/Users/benig/.local/share/nvim/plugged/iron.nvim/rplugin/python3/iron: No module named 'iron.zen'                                                                                           Traceback (most recent call last):                                                                                        File "C:\tools\miniconda3\lib\site-packages\neovim\plugin\host.py", line 130, in _load                                    module = imp.load_module(name, file, pathname, descr)                                                                 File "C:\tools\miniconda3\lib\imp.py", line 245, in load_module                                                           return load_package(name, filename)                                                                                   File "C:\tools\miniconda3\lib\imp.py", line 217, in load_package                                                          return _load(spec)                                                                                                    File "<frozen importlib._bootstrap>", line 684, in _load                                                                File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                     ModuleNotFoundError: No module named 'iron.zen'                                                                         Encountered ModuleNotFoundError loading plugin at C:/Users/benig/.local/share/nvim/plugged/iron.nvim/rplugin/python3/migrate.py: No module named 'iron'                                                                                         Traceback (most recent call last):                                                                                        File "C:\tools\miniconda3\lib\site-packages\neovim\plugin\host.py", line 130, in _load                                    module = imp.load_module(name, file, pathname, descr)                                                                 File "C:\tools\miniconda3\lib\imp.py", line 235, in load_module                                                           return load_source(name, filename, file)                                                                              File "C:\tools\miniconda3\lib\imp.py", line 172, in load_source                                                           module = _load(spec)                                                                                                  File "<frozen importlib._bootstrap>", line 684, in _load                                                                File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                                     ModuleNotFoundError: No module named 'iron'                                                                             remote/host: python3 host registered plugins ['deoplete']                                                               remote/host: generated rplugin manifest: C:\Users\benig\AppData\Local\/nvim/rplugin.vim`

I am running neovim latest version under windows with both python2 and 3 support. Anything I am doing wrong ?

Thanks for your help,
Benigno.

**Comment by hkupty** [comment]
Hi, thanks for the issue.

It seems that, for some reason, it's not able to find the path for `zen`.
I've seen your comment on #59, but it wouldn't hurt double checking that the dependency was actually downloaded (through git submodule).

Also, note that there is a link on `rplugin/python3/iron/` that points to `deps/zen`. Since you're using windows, I bet that the link is not exactly working for you. You could try creating a link yourself instead (I'm not sure how windows deals with this TBH, so my bet is on that).

Last thing if that doesn't work, I suggest you try the branch that will replace python3 with lua, which should be better in terms of compatibility - even though it's still lacking proper support for some languages.

I've never tested iron nor any other plugin on windows so I'm not sure which kinds of flaws/errors would be present and how to solve them. I'm sorry for the inconvenience.

Once again, thanks for the issue and the interest in iron.

Cheers,
Henry

**Comment by benignoc** [comment]
Hello Henry, and thanks for your answer.

    I have already checked the zen dependency is there, and even manually downloaded it just in case there was a difference in versions or something, but without success.

    I have tried checking the link at `rplugin/python3/iron/` and zen appears as a file containing the relative path written in linux format `../../../deps/zen.nvim/src` I have tried both changing the backslashes to windows `..\..\..\deps\zen.nvim\src` and leaving it as a normal file, and also creating a link in windows with command: `mklink /D zen ..\..\..\deps\zen.nvim\src` the link in this way is correctly created and I access the zen/src normally, but in both cases I get the same error on UpdateRemotePlugins.

     I have also tried just copying the contents of `zen.nvim\src` into `rplugin/python3/iron/zen` also with no luck.

     I have then removed the master, and installed the lua/replace branch `Plug 'Vigemus/iron.nvim', { 'branch': 'lua/replace' }` this has worked in that UpdateRemotePlugins no longer gives an error.

Problem now is: 
`The system cannot find the path specified.
E5105: Error while calling lua chunk: ...ig\.local\share\nvim\plugged\iron.nvim\lua\iron\init.lua:106: attempt to index local 'repl' (a nil value)`

Thanks again,
Benigno.

**Comment by hkupty** [comment]
Hi again Benigno,

From my understanding (as I don't have a windows machine to test it) the issue should've been solved now.

Do you care to test `lua/replace` once again?

Cheers,
Henry John Kupty

**Comment by hkupty** [comment]
Hi,

Sorry for taking long to follow up.

Glad the lua branch works better for you.

Regarding the two issues you're having now:
- Double check your configurations if anything is deviating the default behavior (such as setting `splitbelow`/`splitright`). Otherwise, it should obey what you specify in `repl_open_cmd`. I'll double check on my side if there's anything wrong.
- Iron uses normal `terminal` commands from neovim. To escape them, you should use (as per the default terminal behavior) `<C-\><C-n>`. You can find more about that with `:h terminal`.
If you've ever used `tmux`, I recommend [nvimux](https://github.com/Vigemus/nvimux) as it'll bind `tmux` bindings to your neovim.

I hope this helps solving your issues.

Cheers,
Henry John Kupty

**Comment by benignoc** [comment]
Hello Henry, and thanks for your answer.

     I couldnt get, even removing the setting `splitbelow` or `splitright` to have it open below, but then maybe I have some configuration setting that might be interfeering, or its the terminal being used (doing it on nvim-qt). 

     As for escaping, that worked fine, I have been using TMux and its the way to work with all these things that I prefer, but I havent found a way to do it properly on windows. (Short of doing it from the WSL ubuntu install that I have, but I find thats not practical for continuous work).

Thanks a lot for your help,
Benigno.
PS: I think this may have derived quite a bit from original intent, and I feel it can be closed if you wish. Thanks again for your support.

**Comment by r-tanner-f** [comment]
`lua/replace` branch working for me on Windows 10.

Same split issue, but that sounds separate. Not sure if it's Windows related.

**Comment by hkupty** [comment]
#91 created to investigate the issue mentioned by @benignoc and @r-tanner-f.

I'll close this one.

Thanks for helping making iron.nvim better folks.

Cheers,
Henry

**Comment by benignoc** [comment]
Thank you.
